### PR TITLE
Reviewer penalty

### PR DESCRIPTION
**Pull request by g4s8**
zerocracy/farm#1927 - added reviewer penalty of `-32` points

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#70](https://github.com/zerocracy/zerocracy.github.io/issues/70) is now in scope, role is `REV`

**Comment by yegor256** [comment]
@g4s8 thanks

**Comment by 0crat** [comment]
Job `gh:zerocracy/zerocracy.github.io#70` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#70](https://github.com/zerocracy/zerocracy.github.io/issues/70) is now out of scope

**Pull request merged**
