### PR TITLE
Missed announcement info

### PR DESCRIPTION
**Pull request by g4s8**
Added vacancies details for https://github.com/zerocracy/farm/issues/971 job.

### CODE REVIEW

**Comment by g4s8** [comment]
@yegor256 please look at this PR

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this pull request is too small, just 2 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @g4s8[/z](https://www.0crat.com/u/g4s8) please review this and merge or reject

**Comment by yegor256** [comment]
@g4s8 thanks!

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zerocracy/zerocracy.github.io#21` is not assigned, can't get performer

**Pull request merged**
