### PR TITLE
Fix grammar and spelling typos in Policy

### PR DESCRIPTION
**Pull request by alhadhrami**
Fix grammar and spelling typos

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#41](https://github.com/zerocracy/zerocracy.github.io/issues/41) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#41](https://github.com/zerocracy/zerocracy.github.io/issues/41) is assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1921248988); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by krzyk** [comment]
@rultor merge

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/zerocracy/zerocracy.github.io/issues/41#issuecomment-404176186); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by krzyk** [comment]
@yegor256 good to merge

**Comment by krzyk** [comment]
@alhadhrami you need to merge master

**Comment by alhadhrami** [comment]
@krzyk a new commit made outside of this PR caused a conflict. This should be good to merge now.

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by krzyk** [comment]
@yegor256 could we merge?

**Comment by yegor256** [comment]
@alhadhrami thanks!

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#41](https://github.com/zerocracy/zerocracy.github.io/issues/41) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by ypshenychka** [comment]
@krzyk According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>The code reviewer found at least three problems in the code.
Comments were mostly about design problems, not cosmetic issues.

No issues were found during code review. 
Please confirm that you'll try to find at least three major problems while future reviews.

**Comment by ypshenychka** [comment]
@alhadhrami According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Pull request description explains the solution proposed and contains a link to the original ticket it is related to

Please add link to issue into PR's desccription.

**Comment by ypshenychka** [comment]
@alhadhrami According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All commit messages have links to issues

Please confirm you'll try to follow this rule next time.

**Comment by krzyk** [comment]
@ypshenychka I confirm

**Comment by ypshenychka** [comment]
@krzyk thanks

**Comment by alhadhrami** [comment]
@ypshenychka I confirm, but what if this PR is not related to any issue? It's just a general open source contribution. I would like to know what to do in case I plan to contribute more in the future.

**Comment by ypshenychka** [comment]
@alhadhrami great, thanks. Let's ask @yegor256. Should we apply QA rules anyway and follow the flow: issue -> pull request?

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Pull request merged**
