### PR TITLE
Proofreading toc - minor changes

### PR DESCRIPTION
**Pull request by nqafield**

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#15](https://github.com/zerocracy/zerocracy.github.io/issues/15) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#15](https://github.com/zerocracy/zerocracy.github.io/issues/15) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1101357056); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer

**Comment by nqafield** [comment]
@yegor256 It's not obvious why "we encourage egoism" links to the "principles of bug-tracking" post. Is that intentional though?

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by carlosmiranda** [comment]
@yegor256 ping

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#15](https://github.com/zerocracy/zerocracy.github.io/issues/15) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by ypshenychka** [comment]
@nqafield According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Pull request description explains the solution proposed and contains a link to the original ticket it is related to.

Please provide appropriate description with link to original issue in it.

**Comment by ypshenychka** [comment]
@carlosmiranda According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>The code reviewer found at least three problems in the code.
Comments were mostly about design problems, not cosmetic issues.

No issues were found during code review.
Please confirm that you'll try to find at least three problems while future reviews.

**Comment by nqafield** [comment]
@ypshenychka Hi. This is a bit new to me, so apologies. I was asked by @yegor256 in an email (so there is no issue as such, although I guess I could've stated that in the description) to proofread some of the Zerocracy text (I usually do blog posts). I thought I'd try this short markdown doc to get into the swing of it. If this needs to be done a bit differently I'm happy to learn how.

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by nqafield** [comment]
@ypshenychka Code review? What code? And you've still not said who's not getting paid.

**Comment by ypshenychka** [comment]
@nqafield Reviewer is @carlosmiranda and he's not paid.

**Pull request merged**
