### PR TITLE
Corrected invitation paragraph

### PR DESCRIPTION
**Pull request by g4s8**
#54 - corrected invitation paragraph

### CODE REVIEW

**Comment by krzyk** [comment]
@g4s8 won't we need to modify farm code first, to remove reference to `<span id="1.price">`? Without resume processing will be a bit broken (throwing exceptions).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this pull request is too small, just 5 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @g4s8[/z](https://www.0crat.com/u/g4s8) please review this and merge or reject

**Comment by g4s8** [comment]
@krzyk reference to `1.price` was removed in PR https://github.com/zerocracy/farm/pull/1734 and released in `0.34.4`: https://github.com/zerocracy/farm/issues/1733#issuecomment-425630020

**Comment by krzyk** [comment]
@g4s8 thanks

**Comment by krzyk** [comment]
@rultor merge

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/zerocracy/zerocracy.github.io/issues/59#issuecomment-425654738); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by krzyk** [comment]
@g4s8 good to merge

**Comment by yegor256** [comment]
@krzyk merged

**Pull request merged**
