### PR TITLE
Added become-a-qa post

### PR DESCRIPTION
**Pull request by g4s8**
New post to explain how to join Zerocracy as QA

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#75](https://github.com/zerocracy/zerocracy.github.io/issues/75) is now in scope, role is `REV`

**Comment by yegor256** [comment]
@g4s8 thanks! let me publish it now

**Comment by 0crat** [comment]
Job `gh:zerocracy/zerocracy.github.io#75` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#75](https://github.com/zerocracy/zerocracy.github.io/issues/75) is now out of scope

**Pull request merged**
