### PR TITLE
zerocracy/farm#899 Auto-vacation in policy

### PR DESCRIPTION
**Pull request by carlosmiranda**
zerocracy/farm#899: Auto-vacation rule described in policy.

### CODE REVIEW

**Comment by carlosmiranda** [comment]
@yegor256 ping

**Comment by carlosmiranda** [comment]
@yegor256 ping... waiting for nearly two weeks here now

**Comment by carlosmiranda** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
