### PR TITLE
Post about code review

### PR DESCRIPTION
**Pull request by g4s8**
Code review tips

### CODE REVIEW

**Comment by yegor256** [comment]
@g4s8 thanks!

**Comment by yegor256** [comment]
@g4s8 published in d22d818

**Comment by 0crat** [comment]
Job `gh:zerocracy/zerocracy.github.io#79` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#79](https://github.com/zerocracy/zerocracy.github.io/issues/79) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Pull request merged**
