### PR TITLE
Proofreading "How Long It Takes to Close"

### PR DESCRIPTION
**Pull request by nqafield**
(754 words)

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#61](https://github.com/zerocracy/zerocracy.github.io/issues/61) is now in scope, role is `REV`

**Comment by yegor256** [comment]
@nqafield thanks!

**Comment by 0crat** [comment]
Job `gh:zerocracy/zerocracy.github.io#61` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#61](https://github.com/zerocracy/zerocracy.github.io/issues/61) is now out of scope

**Pull request merged**
